analyzer:
  errors:
    unnecessary_statements: ignore
    deprecated_member_use: ignore
    require_trailing_commas: ignore
    avoid_positional_boolean_parameters: ignore
    lines_longer_than_80_chars: ignore
    prefer_if_elements_to_conditional_expressions: ignore
    eol_at_end_of_file: ignore
    unused_import: ignore
    unused_element: ignore
    inference_failure_on_instance_creation: ignore
    inference_failure_on_function_invocation: ignore
    unnecessary_lambdas: ignore
    prefer_int_literals: ignore
    unawaited_futures: ignore
    sized_box_for_whitespace: ignore
    avoid_redundant_argument_values: ignore
    cascade_invocations: ignore
    sort_constructors_first: ignore
    avoid_print: ignore
    always_put_required_named_parameters_first: ignore
    use_build_context_synchronously: ignore
    avoid_escaping_inner_quotes: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false